---

- name: fail if state is not recognized
  fail:
    msg: "No se reconoce el estado: {{ m7s_k8s_nginx_ingress_state }}"
  when: 
  - m7s_k8s_nginx_ingress_enabled == true
  - m7s_k8s_nginx_ingress_state not in ["installed", "upgraded", "purged"]

- name: check if namespace is being used
  k8s_facts:
    api_version: v1
    kind: Namespace
    name: "{{ m7s_k8s_nginx_ingress_namespace }}"
  register: namespace_output
  when: m7s_k8s_nginx_ingress_enabled == true
 
- include_tasks: install-and-configure.yml
  when: m7s_k8s_nginx_ingress_enabled
